[workspace]
members = ["kernel"]

[package]
name = "urclos"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = { version = "0.11.6", default-features = false, features = ["bios"] }
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
